packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@trpc/client': ^11.6.0
  '@trpc/server': ^11.6.0
  lucide-react: ^0.544.0
  tailwindcss: ^4.1.14
  typescript: ^5.9.3
  zod: 4.1.11

catalogs:
  react19:
    '@types/react': ^19.2.0
    '@types/react-dom': ^19.2.0
    react: 19.2.0
    react-dom: 19.2.0

linkWorkspacePackages: true

nodeLinker: hoisted
